version: "3.7"
services:
  aws-cli:
    tty: true
    volumes:
      - ./data/:/root/data/
    build:
      context: ./aws-cli
      dockerfile: Dockerfile
      args:
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    environment:
      SERVERLESS_ACCESS_KEY_ID: ${SERVERLESS_ACCESS_KEY_ID}
      SERVERLESS_SECRET_ACCESS_KEY: ${SERVERLESS_SECRET_ACCESS_KEY}
